WebRTCTestApp/Models/IdModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebRTCTestApp.Models
{
    public class ShowRoomModel
    {
        public Guid RoomId { get; set; }
        public Guid UserId { get; set; }
    }
}

WebRTCTestApp/Models/Room.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebRTCTestApp.Models
{
    public class Room
    {
        public List<string> Users { get; set; }
    }
}

WebRTCTestApp/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebRTCTestApp.Models
{
    public class User
    {
        public string ConnectionId { get; set; }
    }
}

WebRTCTestApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebRTCTestApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebRTCTestApp/Controllers/WebRTCController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebRTCTestApp.Models;

namespace WebRTCTestApp.Controllers
{
    public class WebRTCController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ShowRoom(Guid? roomId)
        {
            var model = new ShowRoomModel { RoomId = roomId == null ? Guid.NewGuid() : roomId.Value };
            return View("Room", model);
        }
    }
}

WebRTCTestApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebRTCTestApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebRTCTestApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
<div>@Html.ActionLink("Create room","ShowRoom","WebRTC")</div>
</div>

WebRTCTestApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Back", "Index", "WebRTC", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @*<ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebRTCTestApp/Views/WebRTC/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <div class="cont">
        @Html.ActionLink("Create Room","ShowRoom",null,new {@class ="btn btn-primary"})
    </div>

WebRTCTestApp/Views/WebRTC/Room.cshtml
@model WebRTCTestApp.Models.ShowRoomModel
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">
    (function (global, undefined) {
        global.roomId = "@Model.RoomId.ToString("N")";
    })(this);
</script>
<div id="container" class="row">
    <div class="col-md-6">
        <div class="videoDiv my">
            <p>Your video</p>
            <div class="noVideoDiv my">
                Video not available
            </div>
            <video autoplay class="video mine" muted="muted"></video>
        </div>
    </div>
    <div class="col-md-6">
        <div class="videoDiv remote">
            <p>Remote video</p>
            <div class="noVideoDiv remote">
                Video not available
            </div>
            <video autoplay class="video remote"></video>
            <div class="video-controls">
                <button type="button" id="play-pause" class="btn btn-default">
                    <span class="glyphicon glyphicon-pause"></span>
                </button>
                <button type="button" id="mute" class="btn btn-default">
                    <span class="glyphicon glyphicon-volume-off"></span>
                </button>
                <input type="range" id="volumebar">
                <button type="button" id="fullscreen" class="btn btn-default">
                    <span class="glyphicon glyphicon-fullscreen"></span>
                </button>
            </div>
        </div>
    </div>
</div>
<div class="container chat">
    <div id="chatMessages"></div>
    <div id="formControls">
        <textarea class="form-control input-lg" id="message"></textarea>
        <span class="btn btn-default btn-file btn-lg" id="fileInput">
            Browse <input type="file" id="input">
        </span>
        <button id="sendMessage" class="btn btn-default btn-lg" type="button">Send</button>
    </div>
</div>
@Html.ActionLink("Connect to this room", "ShowRoom", new { roomId = Model.RoomId })

<script src="/Scripts/jquery-1.10.2.min.js"></script>
<script src="/Scripts/jquery.signalR-2.1.2.min.js"></script>
<script src="~/signalr/hubs"></script>
<script src="/Scripts/adapter.js"></script>
<script src="/Scripts/RTCPeerConnection.js"></script>
<script src="/Scripts/videoControls.js"></script>